import { useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { FileText, Download, Loader2, AlertCircle } from 'lucide-react';
import { useCases } from '../hooks/useCases';
import { reportsApi, type InvestigationReport } from '../services/api';
import { EASE } from '../components/motion/primitives';

function formatSimilarity(value: number): string {
    return `${Math.round(value * 100)}%`;
}

function formatDate(value: string): string {
    return new Date(value).toLocaleDateString();
}

function buildMarkdown(report: InvestigationReport): string {
    const lines: string[] = [];
    lines.push(`# Investigation Report`);
    lines.push('');
    lines.push(`**Case ID:** ${report.case_id}`);
    if (report.query_name) lines.push(`**Subject:** ${report.query_name}`);
    if (report.query_age !== undefined && report.query_age !== null) {
        lines.push(`**Age:** ${report.query_age}`);
    }
    lines.push(`**Generated:** ${new Date(report.generated_at).toLocaleString()}`);
    lines.push(`**Records searched:** ${report.total_records}`);
    lines.push('');
    lines.push(`## Summary`);
    lines.push(report.summary);
    lines.push('');
    lines.push(`## Key Findings`);
    report.findings.forEach((f) => lines.push(`- ${f}`));
    lines.push('');
    lines.push(`## Top Candidates`);
    report.candidates.forEach((c) => {
        lines.push(
            `- Rank ${c.rank}: person ${c.person_id} (age ${c.age}, ${c.dataset}) - ${formatSimilarity(c.face_similarity)}`
        );
    });
    lines.push('');
    lines.push(`## Recommendations`);
    report.recommendations.forEach((r) => lines.push(`- ${r}`));
    lines.push('');
    lines.push(`## Next Steps`);
    report.next_steps.forEach((s) => lines.push(`- ${s}`));
    lines.push('');
    lines.push('---');
    lines.push('*This report was generated by PehchaanAI. For investigative use only.*');
    return lines.join('\n');
}

function ReportSection({ title, items }: { title: string; items: string[] }) {
    return (
        <div>
            <h4 className="font-display font-semibold text-white/90 text-sm mb-2">{title}</h4>
            <ul className="space-y-1.5">
                {items.map((item, i) => (
                    <li key={i} className="flex gap-2 text-sm text-white/60">
                        <span className="text-brand-400 flex-shrink-0">•</span>
                        <span>{item}</span>
                    </li>
                ))}
            </ul>
        </div>
    );
}

export function ReportsPage() {
    const { data: cases, isLoading } = useCases({ limit: 100 });
    const reducedMotion = useReducedMotion();
    const [selectedCase, setSelectedCase] = useState<string | null>(null);
    const [generatingReport, setGeneratingReport] = useState(false);
    const [report, setReport] = useState<InvestigationReport | null>(null);
    const [error, setError] = useState<string | null>(null);

    const handleGenerateReport = async () => {
        if (!selectedCase) return;
        setGeneratingReport(true);
        setReport(null);
        setError(null);
        try {
            const generated = await reportsApi.generate(selectedCase);
            setReport(generated);
        } catch (err) {
            setError('Failed to generate the report. Check that the backend is running.');
        } finally {
            setGeneratingReport(false);
        }
    };

    const handleDownloadReport = () => {
        if (!report) return;
        const blob = new Blob([buildMarkdown(report)], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `report-${report.case_id.slice(0, 8)}-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-6">
            <div>
                <div className="flex items-center gap-2 mb-1">
                    <span className="mono-label">Intelligence / Findings</span>
                </div>
                <h1 className="text-3xl lg:text-4xl font-display font-bold text-white tracking-tight leading-none">
                    AI Reports
                </h1>
                <p className="mt-2 text-white/50 text-sm">
                    Generate investigation reports from case results and search data
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <motion.div
                    className="lg:col-span-1"
                    initial={reducedMotion ? false : { opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: EASE }}
                >
                    <div className="card-glass rounded-xl p-6 h-full flex flex-col tick-corners">
                        <h2 className="font-display font-semibold text-white mb-4">Select Case</h2>

                        <div className="flex-1 space-y-2 overflow-y-auto max-h-80">
                            {isLoading ? (
                                [1, 2, 3].map((i) => (
                                    <div key={i} className="h-14 bg-white/5 rounded-xl animate-pulse" />
                                ))
                            ) : cases && cases.length > 0 ? (
                                cases.map((caseItem) => (
                                    <button
                                        key={caseItem.id}
                                        onClick={() => setSelectedCase(caseItem.id)}
                                        className={`w-full text-left p-3 rounded-xl border transition-colors ${
                                            selectedCase === caseItem.id
                                                ? 'border-brand-500/50 bg-brand-500/10 ring-1 ring-brand-500/20'
                                                : 'border-white/10 hover:border-white/20 hover:bg-white/[0.03]'
                                        }`}
                                    >
                                        <p className="font-medium text-white text-sm">
                                            {caseItem.query_name || 'Unnamed Case'}
                                        </p>
                                        <p className="text-xs text-white/40 mt-0.5">
                                            Created: {formatDate(caseItem.created_at)}
                                        </p>
                                    </button>
                                ))
                            ) : (
                                <div className="text-center py-6 text-white/40">
                                    <FileText className="h-8 w-8 mx-auto text-white/20" />
                                    <p className="mt-2 text-sm">No cases available</p>
                                </div>
                            )}
                        </div>

                        <button
                            onClick={handleGenerateReport}
                            disabled={!selectedCase || generatingReport}
                            className="w-full mt-4 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-brand-500 to-violet-600 text-white text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-glow-brand hover:-translate-y-0.5 transition-all duration-200"
                        >
                            {generatingReport ? (
                                <Loader2 className="h-4 w-4 animate-spin" />
                            ) : (
                                <FileText className="h-4 w-4" />
                            )}
                            {generatingReport ? 'Generating...' : 'Generate Report'}
                        </button>
                    </div>
                </motion.div>

                <motion.div
                    className="lg:col-span-2"
                    initial={reducedMotion ? false : { opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: EASE, delay: 0.1 }}
                >
                    <div className="card-glass rounded-xl p-6 tick-corners">
                        <div className="flex items-center justify-between mb-4">
                            <h2 className="font-display font-semibold text-white">Report Preview</h2>
                            {report && (
                                <button
                                    onClick={handleDownloadReport}
                                    className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-sm text-white/80 hover:bg-white/10 transition-colors"
                                >
                                    <Download className="h-4 w-4" />
                                    Download MD
                                </button>
                            )}
                        </div>

                        {generatingReport ? (
                            <div className="flex flex-col items-center justify-center py-16">
                                <div className="relative">
                                    <Loader2 className="h-10 w-10 text-brand-400 animate-spin" />
                                    <div className="absolute inset-0 h-10 w-10 rounded-full bg-brand-400/20 blur-xl animate-pulse" />
                                </div>
                                <p className="mt-6 text-white/60 font-medium">Generating report...</p>
                            </div>
                        ) : report ? (
                            <div className="space-y-6">
                                <div>
                                    <h3 className="text-lg font-semibold text-white">
                                        {report.query_name || 'Investigation Report'}
                                    </h3>
                                    <p className="text-xs text-white/40 mt-1">
                                        Case {report.case_id.slice(0, 8)}... · Generated{' '}
                                        {new Date(report.generated_at).toLocaleString()} ·{' '}
                                        {report.total_records} records searched
                                    </p>
                                </div>

                                <div className="flex flex-wrap gap-2 text-xs">
                                    <span className="px-2.5 py-1 rounded-full bg-emerald-500/15 text-emerald-300 border border-emerald-500/20">
                                        {report.high_confidence} high confidence
                                    </span>
                                    <span className="px-2.5 py-1 rounded-full bg-amber-500/15 text-amber-300 border border-amber-500/20">
                                        {report.medium_confidence} medium confidence
                                    </span>
                                    <span className="px-2.5 py-1 rounded-full bg-rose-500/15 text-rose-300 border border-rose-500/20">
                                        {report.low_confidence} low confidence
                                    </span>
                                </div>

                                <p className="text-sm text-white/70 leading-relaxed">{report.summary}</p>

                                {report.candidates.length > 0 && (
                                    <div>
                                        <h4 className="font-display font-semibold text-white/90 text-sm mb-2">
                                            Top Candidates
                                        </h4>
                                        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                                            {report.candidates.map((candidate) => (
                                                <div
                                                    key={candidate.record_id}
                                                    className="rounded-xl border border-white/10 bg-white/[0.03] overflow-hidden"
                                                >
                                                    <img
                                                        src={candidate.photo_path}
                                                        alt={`Person ${candidate.person_id}`}
                                                        className="h-28 w-full object-cover bg-white/5"
                                                    />
                                                    <div className="p-2.5">
                                                        <p className="text-sm font-medium text-white truncate">
                                                            Person {candidate.person_id}
                                                        </p>
                                                        <p className="text-xs text-white/40">
                                                            Age {candidate.age} · {candidate.dataset}
                                                        </p>
                                                        <p className="text-xs text-brand-300 mt-1">
                                                            {formatSimilarity(candidate.face_similarity)} match
                                                        </p>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}

                                <ReportSection title="Key Findings" items={report.findings} />
                                <ReportSection title="Recommendations" items={report.recommendations} />
                                <ReportSection title="Next Steps" items={report.next_steps} />
                            </div>
                        ) : error ? (
                            <div className="flex flex-col items-center justify-center py-16 text-center">
                                <AlertCircle className="h-10 w-10 text-rose-400" />
                                <h3 className="mt-4 text-lg font-semibold text-white/80">
                                    Report generation failed
                                </h3>
                                <p className="mt-2 text-white/40 text-sm">{error}</p>
                            </div>
                        ) : (
                            <div className="flex flex-col items-center justify-center py-16 text-center">
                                <div className="h-14 w-14 rounded-xl bg-white/5 flex items-center justify-center mb-4">
                                    <FileText className="h-6 w-6 text-white/30" />
                                </div>
                                <h3 className="text-lg font-semibold text-white/80">
                                    No report generated
                                </h3>
                                <p className="mt-2 text-white/40 text-sm">
                                    Select a case and generate a report to preview it here
                                </p>
                            </div>
                        )}
                    </div>
                </motion.div>
            </div>
        </div>
    );
}