import { useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { FileText, Download, Loader2, AlertCircle, CheckCircle2 } from 'lucide-react';
import { useCases } from '../hooks/useCases';
import { EASE } from '../components/motion/primitives';

export function ReportsPage() {
    const { data: cases, isLoading } = useCases({ limit: 100 });
    const reducedMotion = useReducedMotion();
    const [selectedCase, setSelectedCase] = useState<string | null>(null);
    const [generatingReport, setGeneratingReport] = useState(false);
    const [report, setReport] = useState<string | null>(null);

    const handleGenerateReport = async () => {
        if (!selectedCase) return;
        setGeneratingReport(true);
        setReport(null);

        await new Promise((resolve) => setTimeout(resolve, 2000));

        setReport(`
## Investigation Report

**Case ID:** ${selectedCase.slice(0, 8)}...
**Generated:** ${new Date().toLocaleString()}

### Summary
This report provides an analysis of the investigation case and search results.

### Key Findings
1. Face detection was successfully performed on the query image
2. Multiple candidate matches were found in the database
3. Top candidates have similarity scores above the threshold

### Recommendations
1. Prioritize investigation of candidates with similarity scores above 80%
2. Consider age progression analysis for long-term missing persons
3. Cross-reference with external databases for additional leads

### Next Steps
- Review top candidate matches
- Coordinate with field investigators
- Update case status based on findings

---
*This report was generated by PehchaanAI. For investigative use only.*
    `.trim());

        setGeneratingReport(false);
    };

    const handleDownloadReport = () => {
        if (!report) return;
        const blob = new Blob([report], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `report-${selectedCase?.slice(0, 8) || 'unknown'}-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-6">
            <div>
                <h1 className="text-2xl lg:text-3xl font-display font-bold text-white tracking-tight">AI Reports</h1>
                <p className="mt-1 text-white/50 text-sm">Generate investigation reports powered by AI</p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <motion.div
                    className="lg:col-span-1"
                    initial={reducedMotion ? false : { opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: EASE }}
                >
                    <div className="card-glass rounded-2xl p-6 h-full flex flex-col">
                        <h2 className="font-display font-semibold text-white mb-4">Select Case</h2>

                        <div className="flex-1 space-y-2 overflow-y-auto max-h-80">
                            {isLoading ? (
                                [1, 2, 3].map((i) => (
                                    <div key={i} className="h-14 bg-white/5 rounded-xl animate-pulse" />
                                ))
                            ) : cases && cases.length > 0 ? (
                                cases.map((caseItem) => (
                                    <button
                                        key={caseItem.id}
                                        onClick={() => setSelectedCase(caseItem.id)}
                                        className={`w-full text-left p-3 rounded-xl border transition-colors ${
                                            selectedCase === caseItem.id
                                                ? 'border-brand-500/50 bg-brand-500/10 ring-1 ring-brand-500/20'
                                                : 'border-white/10 hover:border-white/20 hover:bg-white/[0.03]'
                                        }`}
                                    >
                                        <p className="font-medium text-white text-sm">
                                            {caseItem.query_name || 'Unnamed Case'}
                                        </p>
                                        <p className="text-xs text-white/40 mt-0.5">
                                            Created: {new Date(caseItem.created_at).toLocaleDateString()}
                                        </p>
                                    </button>
                                ))
                            ) : (
                                <div className="text-center py-6 text-white/40">
                                    <FileText className="h-8 w-8 mx-auto text-white/20" />
                                    <p className="mt-2 text-sm">No cases available</p>
                                </div>
                            )}
                        </div>

                        <button
                            onClick={handleGenerateReport}
                            disabled={!selectedCase || generatingReport}
                            className="w-full mt-4 inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-brand-500 to-violet-600 text-white text-sm font-medium disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-glow-brand hover:-translate-y-0.5 transition-all duration-200"
                        >
                            {generatingReport ? (
                                <Loader2 className="h-4 w-4 animate-spin" />
                            ) : (
                                <FileText className="h-4 w-4" />
                            )}
                            {generatingReport ? 'Generating...' : 'Generate Report'}
                        </button>
                    </div>
                </motion.div>

                <motion.div
                    className="lg:col-span-2"
                    initial={reducedMotion ? false : { opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: EASE, delay: 0.1 }}
                >
                    <div className="card-glass rounded-2xl p-6 h-full">
                        <div className="flex items-center justify-between mb-4">
                            <h2 className="font-display font-semibold text-white">Report Preview</h2>
                            {report && (
                                <button
                                    onClick={handleDownloadReport}
                                    className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-sm text-white/80 hover:bg-white/10 transition-colors"
                                >
                                    <Download className="h-4 w-4" />
                                    Download
                                </button>
                            )}
                        </div>

                        {generatingReport ? (
                            <div className="flex flex-col items-center justify-center py-16">
                                <div className="relative">
                                    <Loader2 className="h-10 w-10 text-brand-400 animate-spin" />
                                    <div className="absolute inset-0 h-10 w-10 rounded-full bg-brand-400/20 blur-xl animate-pulse" />
                                </div>
                                <p className="mt-6 text-white/60 font-medium">Generating AI report...</p>
                                <p className="text-sm text-white/40 mt-1">This may take a few seconds</p>
                            </div>
                        ) : report ? (
                            <div className="whitespace-pre-wrap font-mono text-sm text-white/70 bg-black/30 rounded-xl p-6 overflow-x-auto">
                                {report}
                            </div>
                        ) : (
                            <div className="flex flex-col items-center justify-center py-16 text-center">
                                <div className="h-14 w-14 rounded-2xl bg-white/5 flex items-center justify-center mb-4">
                                    <FileText className="h-6 w-6 text-white/30" />
                                </div>
                                <h3 className="text-lg font-semibold text-white/80">No report generated</h3>
                                <p className="mt-2 text-white/40 text-sm">Select a case and generate a report to preview it here</p>
                            </div>
                        )}
                    </div>
                </motion.div>
            </div>

            <motion.div
                className="card-glass rounded-2xl p-4"
                initial={reducedMotion ? false : { opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.6, delay: 0.2 }}
            >
                <div className="flex items-start gap-3">
                    <AlertCircle className="h-5 w-5 text-brand-400 flex-shrink-0 mt-0.5" />
                    <div>
                        <p className="text-sm font-medium text-white/80">Day 6 Feature Preview</p>
                        <p className="text-sm text-white/40 mt-1">
                            Full AI report generation with LLM integration will be implemented on Day 6.
                            This page currently shows a placeholder for the feature.
                        </p>
                    </div>
                </div>
            </motion.div>
        </div>
    );
}
